import Head from 'next/head'
import Image from 'next/image'
import Text from 'next'
import { Inter } from 'next/font/google'
import styles from '@component/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <div className={styles.center}>
          <Text>Loading</Text>
          <div className={styles.thirteen}>
            <Text> in a few</Text>
          </div>
        </div>
      </main>
    </>
  )
}
