import Head from "next/head";
import { Box, Heading, Text, Button, CircularProgress } from "@chakra-ui/react";

import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box textAlign="center" py={10} px={6}>
          <Heading
            display="inline-block"
            as="h2"
            size="2xl"
            bgGradient="linear(to-r, teal.400, teal.600)"
            backgroundClip="text"
          >
            Hello
          </Heading>
          <Text color={"gray.500"} mb={6} mt={6}>
            The portfolio webpage is in maintenance
          </Text>
          <Box p={6}>
           
            <CircularProgress isIndeterminate color="green.300" />
          </Box>

          <Button
            colorScheme="teal"
            bgGradient="linear(to-r, teal.400, teal.500, teal.600)"
            color="white"
            variant="solid"
          >
            Head to Blog
          </Button>
        </Box>
      </main>
    </>
  );
}
